version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: simulador_db
    restart: always
    environment:
      POSTGRES_DB: reservas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MAX_CONNECTIONS: 100
    ports:
      - "5432:5432"
    volumes:
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  app:
    build: ./backend
    container_name: simulador_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: reservas_db
    command: ["go", "run", "main.go", "--users=30", "--isolation=serializable"]
